### ISSUE TITLE
F-Droid build fails due to missing translations

### ISSUE THREAD

**Issue by est31** [quaap/AudioMeter#5]
Hi, I'm an [F-Droid](https://f-droid.org) packager and have seen that the build for version 1.1 has failed on our infrastructure. You can have a look at the output here: https://f-droid.org/wiki/index.php?title=com.quaap.audiometer/lastbuild_2&oldid=120335

The lint fails due to missing translations. It can be fixed by either adding translations where it was pointed out, or by adding something like

```
lintOptions {
    disable 'MissingTranslation'
}
```

to the build.gradle. If you want to reproduce this, call `../gradlew lintVitalRelease` from the app folder.

Thanks!

**Comment by quaap** [comment]
Thanks for the bug report.  I was using Android Studio to compile so it didn't show those errors.  I've corrected this problem in v1.2.0 and it compiles correctly with both Android Studio and Gradle. Thanks!

**Comment by est31** [comment]
@quaap I don't see any changes pushed to github? Maybe forgot to git push?

**Comment by quaap** [comment]
I had fixed it several days ago by merging a pull request from naofum.  I then created a new version: v1.2.0.  So the fix is not in v1.1.0 (I don't think I can add to that release tag?).  I've confirmed v1.2.0 compiles with gradlew. Thanks!

**Comment by est31** [comment]
I see. I also see the 1.2 build already picked up by the automated tooling. Thanks for the info!
