### ISSUE TITLE
New challenge: EMF meter

### ISSUE THREAD

**Issue by davidhedlund** [quaap/AudioMeter#6]
>  I noticed there was no audio meter in F-Droid, so I thought I'd build one from scratch. Currently this as a simple way to monitor relative sound levels (not "loudness").

There are tons of EMF meters (aka sold as "ghost hunters") on play.google.com, but not a single one on f-droid.org. I cannot find any EMF meter for Android that is distributed under a free software license.

**Comment by quaap** [comment]
Ha, that'd be pretty good.  I'm not sure it's really possible though without special hardware.  Many phones have a magnetometer, but that will only pick up magnetic fields, not EM waves, and the cell-radio is by-definition an EM detector, but we can't really use it through the APIs and it is tuned to detect only certain EM bands anyway. 

It'd be cool to fake one with the magnetometer, though! Might look into it :)

**Comment by davidhedlund** [comment]
@quaap Thanks for the explanation. I suppose these software are all fake then. I don't like that.
