### ISSUE TITLE
Another challenge: USB camera

### ISSUE THREAD

**Issue by davidhedlund** [quaap/AudioMeter#8]
There are no USB Camera (like https://play.google.com/store/apps/details?id=infinitegra.trial.usbcamera) on f-droid.org.

It would be useful to connect an endoscope to the smartphone.

**Comment by quaap** [comment]
Fine idea! But I don't have the equipment to test with.  Someone else might be inclined to give it a shot. :)

**Comment by davidhedlund** [comment]
@quaap I can give you a cheap endoscope + OTG adapter so you can connect it to your smartphone.

**Comment by davidhedlund** [comment]
Are you interested?

**Comment by quaap** [comment]
I only have so much time available to me, and I fear that project would probably be put on the back-burner indefinitely.  Like I said, it's a fine idea, but I'm not the person for it.  Sorry.

**Comment by davidhedlund** [comment]
@quaap I respect your decision. I wonder where I could find the appropriate person.
